In [22]:
import matplotlib.pyplot as plt
import scipy.stats as stats
import pandas as pd

In [19]:
data = pd.read_csv("clean_data.csv")

data.head()

,Unnamed: 0,Transaction_ID,Transaction_Amount (in Million),Transaction_Time,Transaction_Date,Transaction_Type,Merchant_Category,Transaction_Location,Customer_Home_Location,Distance_From_Home,...,Daily_Transaction_Count,Weekly_Transaction_Count,Avg_Transaction_Amount (in Million),Max_Transaction_Last_24h (in Million),Is_International_Transaction,Is_New_Merchant,Failed_Transaction_Count,Unusual_Time_Transaction,Previous_Fraud_Count,Is_Fraud
0,0,431438.0,6.0,10:54,2025-03-08,POS,ATM,Singapore,Lahore,466.0,...,4.0,17.0,2.0,4.0,1,1,0.0,0,1.0,0
1,1,902451.0,9.0,19:23,2025-01-17,ATM,ATM,Singapore,Lahore,215.0,...,4.0,9.0,5.0,8.0,1,1,1.0,0,1.0,0
2,2,223410.0,3.0,10:20,2025-04-30,POS,Electronics,Faisalabad,Faisalabad,216.0,...,5.0,18.0,5.0,8.0,1,0,0.0,1,1.0,0
3,3,145626.0,1.0,14:11,2025-02-21,Online,Grocery,London,Karachi,408.0,...,6.0,18.0,5.0,1.0,0,1,2.0,1,1.0,0
4,4,414637.0,1.0,04:12,2025-04-11,Online,Electronics,Singapore,Islamabad,209.0,...,3.0,18.0,4.0,3.0,0,1,1.0,0,1.0,0

## Chi Squared test between Transaction Type and Fraudulent Label

H_0 = No significant relationship between transaction type and fraud
H_a = There is a significant relationship between transaction type and fraud

In [16]:
table = data.pivot_table(
    values='Transaction_ID',
    index='Transaction_Type',
    columns='Is_Fraud',
    aggfunc='count',
    margins=True,
    margins_name='Total'
)

table

Is_Fraud              0     1  Total
Transaction_Type
ATM               15841   796  16637
Online            15831   840  16671
POS               15786   782  16568
Total             47458  2418  49876

In [18]:
contingency_table = pd.crosstab(data['Transaction_Type'], data['Is_Fraud'])
contingency_table

Is_Fraud              0    1
Transaction_Type
ATM               15841  796
Online            15831  840
POS               15786  782

In [23]:
chi2, p, dof, expected = stats.chi2_contingency(contingency_table)

print(f"Chi2 Statistic: {chi2}")
print(f"P-value: {p}")

Chi2 Statistic: 2.04844915616671
P-value: 0.3590747919451455

In [24]:
df = 2
alpha = 0.05

critical_value = stats.chi2.ppf(1 - alpha, df)
critical_value

np.float64(5.99146454710798)