In [19]:
import pandas as pd

data = pd.read_csv("FraudShield_Banking_Data.csv")

data.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 25 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Transaction_ID                         49997 non-null  float64
 1   Customer_ID                            49990 non-null  float64
 2   Transaction_Amount (in Million)        49991 non-null  float64
 3   Transaction_Time                       49991 non-null  str
 4   Transaction_Date                       49997 non-null  str
 5   Transaction_Type                       49996 non-null  str
 6   Merchant_ID                            49993 non-null  float64
 7   Merchant_Category                      49991 non-null  str
 8   Transaction_Location                   49994 non-null  str
 9   Customer_Home_Location                 49996 non-null  str
 10  Distance_From_Home                     49998 non-null  float64
 11  Device_ID                              49991 non-null  float64
 12  IP_Address                             49994 non-null  str
 13  Card_Type                              49997 non-null  str
 14  Account_Balance (in Million)           49991 non-null  float64
 15  Daily_Transaction_Count                49991 non-null  float64
 16  Weekly_Transaction_Count               49995 non-null  float64
 17  Avg_Transaction_Amount (in Million)    49991 non-null  float64
 18  Max_Transaction_Last_24h (in Million)  49996 non-null  float64
 19  Is_International_Transaction           49996 non-null  str
 20  Is_New_Merchant                        49995 non-null  str
 21  Failed_Transaction_Count               49989 non-null  float64
 22  Unusual_Time_Transaction               49997 non-null  str
 23  Previous_Fraud_Count                   49997 non-null  float64
 24  Fraud_Label                            49996 non-null  str
dtypes: float64(13), str(12)
memory usage: 9.5 MB

In [14]:
data.head(100)

,Transaction_ID,Customer_ID,Transaction_Amount (in Million),Transaction_Time,Transaction_Date,Transaction_Type,Merchant_ID,Merchant_Category,Transaction_Location,Customer_Home_Location,...,Daily_Transaction_Count,Weekly_Transaction_Count,Avg_Transaction_Amount (in Million),Max_Transaction_Last_24h (in Million),Is_International_Transaction,Is_New_Merchant,Failed_Transaction_Count,Unusual_Time_Transaction,Previous_Fraud_Count,Fraud_Label
0,431438.0,24239.0,6.0,10:54,2025-03-08,POS,97028.0,ATM,Singapore,Lahore,...,4.0,17.0,2.0,4.0,Yes,Yes,0.0,No,1.0,Normal
1,902451.0,77250.0,9.0,19:23,2025-01-17,ATM,27515.0,ATM,Singapore,Lahore,...,4.0,9.0,5.0,8.0,Yes,Yes,1.0,No,1.0,Normal
2,223410.0,34294.0,3.0,10:20,2025-04-30,POS,13810.0,Electronics,Faisalabad,Faisalabad,...,5.0,18.0,5.0,8.0,Yes,No,0.0,Yes,1.0,Normal
3,145626.0,92041.0,1.0,14:11,2025-02-21,Online,10501.0,Grocery,London,Karachi,...,6.0,18.0,5.0,1.0,No,Yes,2.0,Yes,1.0,Normal
4,414637.0,71578.0,1.0,04:12,2025-04-11,Online,53569.0,Electronics,Singapore,Islamabad,...,3.0,18.0,4.0,3.0,No,Yes,1.0,No,1.0,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,603311.0,74137.0,2.0,09:25,2025-04-27,Online,32876.0,Restaurant,Singapore,Faisalabad,...,1.0,10.0,4.0,2.0,No,Yes,1.0,No,1.0,Normal
96,478545.0,34516.0,4.0,22:43,2025-04-27,POS,96893.0,Electronics,Lahore,Multan,...,3.0,23.0,5.0,1.0,No,Yes,2.0,No,1.0,Fraud
97,896253.0,57088.0,3.0,16:50,2025-02-17,ATM,92750.0,Electronics,Dubai,Lahore,...,2.0,5.0,1.0,8.0,Yes,Yes,2.0,No,0.0,Normal
98,229720.0,40378.0,9.0,11:55,2025-02-01,POS,98267.0,Fuel,Bangkok,Karachi,...,1.0,18.0,2.0,3.0,Yes,Yes,0.0,No,0.0,Normal
99,975288.0,96726.0,1.0,20:31,2025-01-08,POS,64395.0,Clothing,Dubai,Lahore,...,1.0,6.0,1.0,3.0,No,No,1.0,Yes,0.0,Normal

In [12]:
data.describe()

,Transaction_ID,Customer_ID,Transaction_Amount (in Million),Merchant_ID,Distance_From_Home,Device_ID,Account_Balance (in Million),Daily_Transaction_Count,Weekly_Transaction_Count,Avg_Transaction_Amount (in Million),Max_Transaction_Last_24h (in Million),Failed_Transaction_Count,Previous_Fraud_Count
count,49997.000000,49990.000000,49991.000000,49993.000000,49998.000000,49991.000000,49991.000000,49991.000000,49995.000000,49991.000000,49996.000000,49989.000000,49997.000000
mean,550400.968898,54869.720744,4.999880,54951.375913,300.098564,552563.600088,20.993179,3.999460,12.520032,2.989098,5.016781,0.992798,0.500130
std,259677.602349,26052.824933,2.582025,25983.342481,172.848263,260186.451027,10.685467,2.002833,6.910709,1.413400,2.572913,0.816081,0.500005
min,100043.000000,10005.000000,1.000000,10001.000000,1.000000,100053.000000,3.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000
25%,324445.000000,32259.250000,3.000000,32545.000000,150.000000,327643.500000,12.000000,2.000000,7.000000,2.000000,3.000000,0.000000,0.000000
50%,552115.000000,54720.500000,5.000000,54935.000000,301.000000,553372.000000,21.000000,4.000000,13.000000,3.000000,5.000000,1.000000,1.000000
75%,775942.000000,77542.000000,7.000000,77341.000000,449.000000,779903.500000,30.000000,6.000000,18.000000,4.000000,7.000000,2.000000,1.000000
max,999992.000000,99996.000000,9.000000,99996.000000,599.000000,999989.000000,39.000000,7.000000,24.000000,5.000000,9.000000,2.000000,1.000000

In [20]:
def report(df):
    return pd.DataFrame({
            "dtype": df.dtypes,
            "missing_count": df.isna().sum(),
            "missing_pct": df.isna().mean() * 100,
            "unique_values": df.nunique(),
        }).sort_values(by="missing_pct", ascending=False)

before_report = report(data)
before_report

,dtype,missing_count,missing_pct,unique_values
Failed_Transaction_Count,float64,11,0.022,3
Customer_ID,float64,10,0.020,38353
Transaction_Amount (in Million),float64,9,0.018,9
Transaction_Time,str,9,0.018,1440
Merchant_Category,str,9,0.018,6
Device_ID,float64,9,0.018,48632
Avg_Transaction_Amount (in Million),float64,9,0.018,5
Account_Balance (in Million),float64,9,0.018,37
Daily_Transaction_Count,float64,9,0.018,7
Merchant_ID,float64,7,0.014,38314
IP_Address,str,6,0.012,49994
Transaction_Location,str,6,0.012,10
Weekly_Transaction_Count,float64,5,0.010,24
Is_New_Merchant,str,5,0.010,2
Is_International_Transaction,str,4,0.008,2
Max_Transaction_Last_24h (in Million),float64,4,0.008,9
Fraud_Label,str,4,0.008,2
Customer_Home_Location,str,4,0.008,5
Transaction_Type,str,4,0.008,3
Card_Type,str,3,0.006,2
Transaction_Date,str,3,0.006,121
Unusual_Time_Transaction,str,3,0.006,2
Previous_Fraud_Count,float64,3,0.006,2
Transaction_ID,float64,3,0.006,48638
Distance_From_Home,float64,2,0.004,599

In [28]:
data_new = data.drop(columns=['Customer_ID', 'Merchant_ID', 'Device_ID', ])
data_new.dropna(inplace=True)
data_new.describe()

,Transaction_ID,Transaction_Amount (in Million),Distance_From_Home,Account_Balance (in Million),Daily_Transaction_Count,Weekly_Transaction_Count,Avg_Transaction_Amount (in Million),Max_Transaction_Last_24h (in Million),Failed_Transaction_Count,Previous_Fraud_Count
count,49876.000000,49876.000000,49876.000000,49876.000000,49876.000000,49876.000000,49876.000000,49876.000000,49876.000000,49876.000000
mean,550390.651355,4.999880,300.143135,20.992902,3.999439,12.517283,2.989354,5.016982,0.992622,0.500261
std,259736.531218,2.581608,172.851676,10.684314,2.002595,6.911125,1.413542,2.573092,0.816119,0.500005
min,100043.000000,1.000000,1.000000,3.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000
25%,324307.750000,3.000000,150.000000,12.000000,2.000000,7.000000,2.000000,3.000000,0.000000,0.000000
50%,551948.500000,5.000000,301.000000,21.000000,4.000000,13.000000,3.000000,5.000000,1.000000,1.000000
75%,776076.750000,7.000000,449.000000,30.000000,6.000000,18.000000,4.000000,7.000000,2.000000,1.000000
max,999992.000000,9.000000,599.000000,39.000000,7.000000,24.000000,5.000000,9.000000,2.000000,1.000000

In [32]:
after_report = report(data_new)
after_report

,dtype,missing_count,missing_pct,unique_values
Transaction_ID,float64,0,0.0,48530
Transaction_Amount (in Million),float64,0,0.0,9
Previous_Fraud_Count,float64,0,0.0,2
Unusual_Time_Transaction,str,0,0.0,2
Failed_Transaction_Count,float64,0,0.0,3
Is_New_Merchant,str,0,0.0,2
Is_International_Transaction,str,0,0.0,2
Max_Transaction_Last_24h (in Million),float64,0,0.0,9
Avg_Transaction_Amount (in Million),float64,0,0.0,5
Weekly_Transaction_Count,float64,0,0.0,24
Daily_Transaction_Count,float64,0,0.0,7
Account_Balance (in Million),float64,0,0.0,37
Card_Type,str,0,0.0,2
IP_Address,str,0,0.0,49876
Distance_From_Home,float64,0,0.0,599
Customer_Home_Location,str,0,0.0,5
Transaction_Location,str,0,0.0,10
Merchant_Category,str,0,0.0,6
Transaction_Type,str,0,0.0,3
Transaction_Date,str,0,0.0,121
Transaction_Time,str,0,0.0,1440
Fraud_Label,str,0,0.0,2

In [37]:
data_new['Is_New_Merchant'] = data_new['Is_New_Merchant'].map({'Yes': 1, 'No': 0}, na_action='ignore')
data_new['Is_International_Transaction'] = data_new['Is_International_Transaction'].map({'Yes': 1, 'No': 0},na_action='ignore')

print(data_new['Is_International_Transaction'])

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
         ..
49995   NaN
49996   NaN
49997   NaN
49998   NaN
49999   NaN
Name: Is_International_Transaction, Length: 49876, dtype: float64